### ISSUE TITLE
Crash on 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [AnOpenSauceDev/Methane-mod#76]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_7353(net.minecraft.class_2561, boolean)" because "client.field_1724" is null
	at com.modrinth.methane.client.MethaneClient.ToggleMethaneSetBool(MethaneClient.java:146)
	at net.minecraft.class_433.handler$gbk000$methane$gracefullyHandleDisconnections2(class_433.java:1523)
	at net.minecraft.class_433.method_47632(class_433.java:131)
	at net.minecraft.class_7574.method_46552(class_7574.java:52)
	at net.minecraft.class_433.method_19836(class_433.java:101)
	at net.minecraft.class_433.md5486b9$seamless_loading_screen$lambda$adjust$1$3(class_433.java:2520)
	at com.minenash.seamless_loading_screen.OnLeaveHelper.takeScreenShot(OnLeaveHelper.java:133)
	at net.minecraft.class_757.handler$gpc000$seamless_loading_screen$attemptToTakeScreenshot(class_757.java:9607)
	at net.minecraft.class_757.method_3192(class_757.java:898)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Using the latest version 3.2.0 of Methane. I think it's related with Seamless Loading Screen.
https://modrinth.com/mod/seamless-loading-screen
After I disconnected from a server the game crashed.

**Comment by AnOpenSauceDev** [comment]
It seems that in both of your issues, the player is made null before Seamless Loading Screen can do anything. In your second issue, Methane crashes the game right after it force-saves due to a small bug. I might be able to fix this to an extent by messing with mixin priorities.

**Comment by sternschnaube** [comment]
Thank you much for the fast release. If I encounter something more, I let hear from me again 😁
