### ISSUE TITLE
Crash on 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [AnOpenSauceDev/Methane-mod#77]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_7353(net.minecraft.class_2561, boolean)" because "client.field_1724" is null
	at com.modrinth.methane.client.MethaneClient.ToggleMethaneSetBool(MethaneClient.java:146)
	at net.minecraft.class_433.handler$gbn000$methane$gracefullyHandleDisconnections2(class_433.java:1523)
	at net.minecraft.class_433.method_47632(class_433.java:131)
	at net.minecraft.class_7574.method_46552(class_7574.java:52)
	at net.minecraft.class_433.method_19836(class_433.java:101)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:177)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1297)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Happened this time after closing the game. I was not able to crash it the same again. But I hope it's helpful.

**Comment by AnOpenSauceDev** [comment]
See: #76
